// This file is generated by scripts/generate-legal-consent.mjs. Do not edit manually.
export const legalConsentVersion = "2026-05-13.install-terms.v1";
export const legalConsentDocumentHash = "sha256-b3e58e77697877a815961fccd43c46d97e86cbb2ef60d10b24ee2ead502f78f7";
export const legalConsentDocuments = [
  {
    "id": "installer-terms",
    "path": "docs/legal/INSTALLER_TERMS.md",
    "sha256": "6deb4d33b3d6c33d297e8fb347b6ded7dadc357b7019729157eb6428f0ada737",
    "bytes": 7204
  },
  {
    "id": "openclaw-mit-notice",
    "path": "docs/legal/OPENCLAW_MIT_NOTICE.md",
    "sha256": "fb3f5491d00053be05ed94945cef797ee71f10ac706dde6feb604f6386afc1f5",
    "bytes": 2915
  }
] as const;
