// This file is generated by scripts/generate-legal-consent.mjs. Do not edit manually.
export const legalConsentVersion = "2026-05-13.install-terms.v1";
export const legalConsentDocumentHash = "sha256-d4dbf58ba66ecd0c5019dc90fb3270efca8c8f9208bdb8bc6571433f00fa602c";
export const legalConsentDocuments = [
  {
    "id": "installer-terms",
    "path": "docs/legal/INSTALLER_TERMS.md",
    "sha256": "12c107dd3a065eafd5824a4d9c13d081c9442913772563f9ec0ead03542b8828",
    "bytes": 5798
  },
  {
    "id": "openclaw-mit-notice",
    "path": "docs/legal/OPENCLAW_MIT_NOTICE.md",
    "sha256": "4e8e9f3bd6cb9eeccb40e7086781b46890bddabea1586253f962296af15d5c5e",
    "bytes": 2566
  }
] as const;
