// This file is generated by scripts/generate-legal-consent.mjs. Do not edit manually.
export const legalConsentVersion = "2026-05-13.install-terms.v1";
export const legalConsentDocumentHash = "sha256-ab921dfe905a1ef0c58701ec07668113065399cfe0952966dcc5c9d15ee056cc";
export const legalConsentDocuments = [
  {
    "id": "installer-terms",
    "path": "docs/legal/INSTALLER_TERMS.md",
    "sha256": "ee6487ce922a130e0d6ad11bf9069f968fab06cf1dde76ebeb4f6977bb735393",
    "bytes": 7280
  },
  {
    "id": "openclaw-mit-notice",
    "path": "docs/legal/OPENCLAW_MIT_NOTICE.md",
    "sha256": "9f4299572a307eaeb2940f49b02536ff2c15495d088e1cef12d9de940bfc9b6b",
    "bytes": 2964
  }
] as const;
